### ISSUE TITLE
你好,请问怎么跟TG关联机器人?

### ISSUE THREAD

**Issue by tasty007** [ArnoFrost/ArnoSpring#1]
你好,请问怎么跟TG关联机器人?
比如扫码 , 加群之类的?
有更详细点的描述吗

**Comment by ArnoFrost** [comment]
您好,才看见.

里面有`application-dev.properties` 配置文件 需要填写`openai`的`key`
以及`telegram bot`的`token`分别对应
  `chatbot-api.key`
  `telegram.bot.token`
之后运行`ArnoSpringApplication`,代码主要逻辑在`TelegramManger`这个类中

最近有些忙,可能来不及更新文档

**Comment by ArnoFrost** [comment]
先简易写了个readme 可以到主页看看
